### ISSUE TITLE
Unmodeled blobs results appear hidden behind main window

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#96] opened 2023-10-01 16:23 UTC
Hi,

On 1.06-pre (on MacOS), when launching "unmodeled blobs", the first window where one sets parameters appears in front of the main display, as expected. 

However, the second window, with the results of the search, is created behind the main window, and is completely obscured by it, so that if the user doesn't think to look for it, they will likely assume that the search has not been successful for some reason.

Cheers
Oli

**Comment by pemsley** [comment] 2023-10-02 04:36
FYI, I can't reproduce this on my Mac laptop.

**Comment by olibclarke** [comment] 2023-10-02 10:41
Have you tried executing it in a case where there are no blobs? I think it might only happen to the "Coot found no unexplained blobs" message

**Comment by pemsley** [comment] 2023-10-02 23:23
Thanks - fixed in 78cdc0dcbd2b73ccfff456e060dbb2baf5dd6714.

**Closed** 2023-10-03 06:04 UTC
