### ISSUE TITLE
Preferences are not persistent (Coot 1.1.10)

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#156] opened 2024-08-01 19:50 UTC
Hi Paul,

If I switch "Smooth recentering" off, close coot, and re-open, it reverts back to the default.

**Comment by pemsley** [comment] 2024-10-07 09:28
This seems to be fixed now. I don't know when it became fixed.
Maybe I can't reproduce the problem.

**Closed by pemsley** 2024-10-07 09:28 UTC
